apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app
data:
  GREETING_MESSAGE: "Hello from Kubernetes backend!"
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
