apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}  # v≈°etky pody v namespace
  policyTypes:
    - Ingress
    - Egress
