apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-rules
  namespace: monitoring
  labels:
    release: monitoring          # sedÃ­ s kube-prometheus-stack
spec:
  groups:
    - name: backend.rules
      rules:
        - alert: BackendDown
          expr: |
            kube_deployment_status_replicas_available{namespace="app", deployment="backend"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Backend deployment has no available replicas"
            description: "Backend deployment in namespace 'app' has 0 available replicas for more than 1 minute."

        - alert: BackendHighErrorRate
          expr: |
            rate(http_requests_total{app="backend",status=~"5.."}[5m])
              /
            rate(http_requests_total{app="backend"}[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Backend has high HTTP 5xx error rate"
            description: "More than 10% of HTTP requests to backend end up as 5xx over last 5 minutes."
