apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-app-read-config
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-read-config-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: demo-app-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: demo-app-read-config
  apiGroup: rbac.authorization.k8s.io
