namespace: app
frontend:
  image:
    repository: ghcr.io/johno221/demo-frontend
    tag: "3a041fe"
    pullPolicy: IfNotPresent
  replicaCount: 3
backend:
  image:
    repository: ghcr.io/johno221/demo-backend
    tag: "3a041fe"
    pullPolicy: IfNotPresent
  replicaCount: 3
ingress:
  enabled: true
  host: demo.local
grafana:
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 32000
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "default"
    receivers:
      - name: "default"
        email_configs: [johny.balint@gmail.com]
prometheus:
  service:
    type: NodePort
    nodePort: 32001
