namespace: app

frontend:
  image:
    repository: ghcr.io/johno221/demo-frontend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicaCount: 3

backend:
  image:
    repository: ghcr.io/johno221/demo-backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  replicaCount: 3

ingress:
  enabled: true
  host: demo.local
